SET (DB_HOME "/usr/local/BerkeleyDB.5.1")
SET (DB_INCLUDE_DIR "${DB_HOME}/include/")
SET (DB_LINK_DIR "${DB_HOME}/lib/")
SET (DB_LIBRARY "${DB_LINK_DIR}/libdb.so")

IF (DB_LIBRARY AND DB_INCLUDE_DIR)
    SET(DB_LIBRARIES ${DB_LIBRARY})
    SET(DB_FOUND "YES")
ELSE (DB_LIBRARY AND DB_INCLUDE_DIR)
  SET(DB_FOUND "NO")
ENDIF (DB_LIBRARY AND DB_INCLUDE_DIR)


IF (DB_FOUND)
   #IF (NOT DB_FIND_QUIETLY)
      MESSAGE(STATUS "Found BerkeleyDB: ${DB_LIBRARIES}")
      MESSAGE(STATUS "                : ${DB_INCLUDE_DIR}")
      INCLUDE_DIRECTORIES(${DB_INCLUDE_DIR})
      LINK_DIRECTORIES(${DB_LINK_DIR})
   #ENDIF (NOT DB_FIND_QUIETLY)
ELSE (DB_FOUND)
   #IF (DB_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find BerkeleyDB library")
   #ENDIF (DB_FIND_REQUIRED)
ENDIF (DB_FOUND)

# Deprecated declarations.
SET (NATIVE_DB_INCLUDE_PATH ${DB_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_DB_LIB_PATH ${DB_LIBRARY} PATH)

MARK_AS_ADVANCED(
  DB_LIBRARY
  DB_INCLUDE_DIR
  )